export const RESET_STEP = 'RESET_STEP';
export const SET_BACK_STEP = 'SET_BACK_STEP';
export const SET_NEXT_STEP = 'SET_NEXT_STEP';

export const SEND_DATA_REQUEST = 'SEND_DATA_REQUEST';
export const REQUESTED_DATA_SECCESS = 'SEND_DATA_SECCESS';
export const REQUESTED_DATA_ERROR = 'SEND_DATA_ERROR';
export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
